spring.application.name=NS
spring.datasource.url=jdbc:postgresql://localhost:5432/Nyaaya_Saathi_DB
spring.datasource.username=postgres
spring.datasource.password=kahj

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true